---
apiVersion: v1
kind: Secret
metadata:
  name: git-db-secrets
  namespace: lan-lab-git-ns
type: Opaque
data:
  POSTGRES_DB: Z2l0ZWE= # base64 for "gitea"
  POSTGRES_USER: Z2l0ZWE= # base64 for "gitea"
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 for "password"